In [12]:
import pandas as pd
# 读取数据 ----> read_csv
# df = pd.read_csv("data/sales.csv")
df = pd.read_csv("data/sales.csv",usecols=["订单号","产品类别","产品名称","销售数量","单价"])
# 查看数据
df.head(10)
df.tail(10)
df.describe()
df.info()
df.shape
df.columns
# # 数据处理
# df["销售金额"] = df["销售数量"] * df["单价"]
#
# # 写入数据 ----> to_csv
# df.to_csv("data/sales_01.csv",index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   订单号     1000 non-null   int64
 1   产品类别    1000 non-null   object
 2   产品名称    1000 non-null   object
 3   销售数量    1000 non-null   int64
 4   单价      1000 non-null   int64
dtypes: int64(3), object(2)
memory usage: 39.2+ KB

Index(['订单号', '产品类别', '产品名称', '销售数量', '单价'], dtype='object')

In [31]:
# 数据选择 ---> loc & iloc
df2 = pd.read_csv("data/sales.csv",usecols=["订单号","产品类别","产品名称","销售数量","单价"], index_col="订单号")
# df2

# 1.选择列
# 1.1 单列
# df2["产品名称"]
# 1.2 多列
# df2[["产品名称", "单价"]]
# df2[["产品名称", "单价", "销售数量"]]

# 2. 选择行 --- iloc, loc
# 2.1 iloc ---> 基于行号选择行(不包含结束位置)， 语法: df.iloc[start:stop: step]
# df2.iloc[0:5:1]
# df2.iloc[0:5]
# 2.2 loc ---> 基于索引标签选择行(包含结束位置)， 语法: df.loc[start:stop: step]
df2.loc[5857234132:6896363474:5]

            产品类别  产品名称  销售数量   单价
订单号
5857234132    食品    海苔     5   29
6857752388    服装    袜子     7  -29
6890234923  家居用品  餐具套装    10  199
5812573980    食品    坚果     2   79
5871374068    图书   摄影集     5  129
5854211330    食品    果干     9   59
5837205437    服装    短裤     2  149
6870668206  家居用品    拖把     6   89

In [47]:
df3 = pd.read_csv("data/sales.csv")
#配置项，展示所有的数据
pd.set_option("display.max_rows", None)
# 数据过滤
# 1.获取销售数量>=10的订单数据
df3[df3["销售数量"] >= 10]

# 2.获取产品类别分别为 食品或图书的订单数据
df3[df3["产品类别"].isin(["食品", "图书"])]

# 3.获取单价在 100-200之间的订单数据  between(默认 包含边界)
# 设置边界：inclusive="both"| "neither"| "left" |"right"
df3[df3["单价"].between(79, 199, inclusive="neither")]

# 4. 获取 销售数量 >=8, 并且 单价 >=100 的订单数据  ------>多条件(并且： &， 或： |)
df3[(df3["销售数量"] >=8) & (df3["单价"] >=100)]

# 5. 获取 产品类别为 服装/食品，支付方式为 支付宝/微信支付 的订单数据
df3[(df3["产品类别"].isin(["服装", "食品"])) & (df3["支付方式"].isin(["支付宝", "微信支付"]))]

            订单号 产品类别   产品名称  销售数量   单价 客户所在城市  支付方式        订单日期
4    6801664364   食品     薯片     2   19    NaN  微信支付  2025/06/02
10   5808071569   食品    矿泉水     9   29     重庆   支付宝  2025-06-04
16   5812573980   食品     坚果     2   79     南京  微信支付  2025-06-05
23   6867258691   服装     围巾     8  129     青岛  微信支付  2025-06-07
25   6837065480   服装     毛衣     3  399     深圳  微信支付  2025-06-07
26   5854211330   食品     果干     9   59     长沙   支付宝  2025-06-07
31   5837205437   服装     短裤     2  149     昆明   支付宝  2025-06-08
32   6816687256   服装    运动裤     7  249     杭州   支付宝  2025-06-09
42   5848602769   食品    能量棒     1   49     福州  微信支付  2025-06-12
43   6896687125   食品     果汁     2   39     合肥   支付宝  2025-06-12
49   6842655345   食品     蜂蜜     7   89     天津   支付宝  2025-06-14
55   6840254213   食品    矿泉水    10   29     天津  微信支付  2025-06-15
59   5805524413   食品     牛奶     5   69     上海   支付宝  2025-06-16
61   5876009437   食品     肉脯     7   69     北京  微信支付  2025-06-17
65   6818771197   服装    羽绒服     4  899     合肥  微信支付  2025-06-18
68   6888558142   服装     手套     5   59     昆明  微信支付  2025-06-18
70   5857892499   食品    巧克力     6   59     合肥  微信支付  2025-06-19
71   6881307037   服装     外套     6  599     长沙   支付宝  2025-06-19
72   6882472708   食品  零食大礼包     5   89     福州  微信支付  2025-06-19
76   5835168341   服装     围巾     5  129     南京   支付宝  2025-06-20
80   6832672046   服装     卫衣     2  349     郑州  微信支付  2025-06-21
84   6835930946   服装    休闲裤     2  299     合肥   支付宝  2025-06-23
96   6882159173   食品     蜂蜜     7   89     武汉  微信支付  2025-06-27
97   6847661479   食品     薯片     8   19     重庆   支付宝  2025-06-27
98   5848428039   食品     茶叶    10  199     重庆  微信支付  2025-06-27
99   6868231493   食品     薯片     5   19     南京  微信支付  2025-06-27
100  5832758970   服装     风衣     8  699     上海   支付宝  2025-06-28
102  6893625569   服装     围巾     8  129     深圳   支付宝  2025-06-29
106  5824298537   服装     卫衣     8  349     苏州  微信支付  2025-06-30
108  6826045080   服装     睡衣     3  199     西安   支付宝  2025-06-30
113  5818261249   食品     茶叶     6  199     郑州   支付宝  2025-07-02
116  5854511595   食品  零食大礼包     2   89     武汉   支付宝  2025-07-03
118  6865301539   食品  零食大礼包     4   89     长沙   支付宝  2025-07-03
121  6892321515   食品     坚果    10   79     西安  微信支付  2025-07-04
122  5883797573   食品     麦片     7   49     成都  微信支付  2025-07-04
125  6818053882   食品     牛奶     4   69     广州   支付宝  2025-07-05
133  5817207922   服装    连衣裙     7  499     福州   支付宝  2025-07-07
137  5813233987   食品    方便面     5   49     昆明  微信支付  2025-07-07
140  5831376701   食品     薯片     2   19     武汉  微信支付  2025-07-08
144  6832294234   食品     咖啡     2  129     上海  微信支付  2025-07-09
146  6856378469   服装    半身裙     8  299     天津   支付宝  2025-07-10
147  5800194073   服装     毛衣     6  399     成都   支付宝  2025-07-11
151  5893341133   食品     糖果     7   39     福州  微信支付  2025-07-13
152  6875304597   食品    能量棒     8   49     杭州  微信支付  2025-07-13
155  6862563518   服装    西装裤     7  449     北京  微信支付  2025-07-14
156  6811607405   食品     饼干     6   39     青岛   支付宝  2025-07-14
157  6869448173   食品    巧克力     3   59     天津  微信支付  2025-07-15
159  5811798968   服装     内衣     5   89     南京   支付宝  2025-07-15
160  6821795644   食品     咖啡     8  129     长沙   支付宝  2025-07-15
169  5843474151   服装    西装裤     1  449     深圳  微信支付  2025-07-18
172  6890353450   食品    方便面     5   49     南京   支付宝  2025-07-19
173  6865052496   服装    半身裙     8  299     苏州  微信支付  2025-07-19
174  6805321631   服装     外套     1  599     西安   支付宝  2025-07-19
179  5821778573   服装     衬衫     7  299     杭州  微信支付  2025-07-21
180  6805779311   服装    运动裤     8  249     上海   支付宝  2025-07-21
188  5816285494   食品     牛奶     1   69     郑州   支付宝  2025-07-25
190  5867072555   服装    西装裤     2  449     合肥  微信支付  2025-07-25
191  5876638261   服装     袜子     5   29     西安   支付宝  2025-07-25
192  5874746458   服装    西装裤     1  449     郑州  微信支付  2025-07-25
197  6826667587   服装    连衣裙     5  499     上海  微信支付  2025-07-26
199  6844981163   食品     茶叶     2  199     深圳   支付宝  2025-07-27
202  5828470938   服装     短裤     2  149     南京   支付宝  2025-07-29
210  5868514156   食品     果干    10   59     广州   支付宝  2025-07-31
215  5811267840   服装     短裤     8  149     郑州   支付宝  2025-08-03
216  6874679301   服装    休闲裤     5  299     合肥   支付宝  2025-08-03
220  5853054830   食品     肉脯     1   69     北京  微信支付  2025-08-04
224  5891062479   食品     饼干    10   39     宁波   支付宝  2025-08-04
232  5827118463   食品     面包    10   29     重庆   支付宝  2025-08-07
241  6804390223   食品     糖果     6   39     合肥  微信支付  2025-08-11
247  6889194588   食品    巧克力     5   59     天津   支付宝  2025-08-12
249  6882063897   食品    巧克力     4   59     重庆  微信支付  2025-08-13
255  6874166656   食品     麦片     2   49     南京   支付宝  2025-08-15
256  6888548139   食品    能量棒     7   49     杭州   支付宝  2025-08-16
259  6890392173   食品     茶叶     5  199     武汉   支付宝  2025-08-16
268  6822412203   服装    休闲裤     8  299     合肥   支付宝  2025-08-19
269  5817231648   服装     衬衫     5  299     杭州  微信支付  2025-08-19
277  6890876412   食品     海苔     1   29     武汉  微信支付  2025-08-21
278  6824270558   食品     薯片     1   19     武汉   支付宝  2025-08-22
283  5865254576   食品    方便面     2   49     长沙   支付宝  2025-08-23
284  5864343049   服装     风衣     1  699     合肥  微信支付  2025-08-24
285  6824634614   服装    西装裤     2  449     合肥  微信支付  2025-08-24
288  6820986832   食品     肉脯     3   69     广州   支付宝  2025-08-24
292  5877457110   食品     蜂蜜     2   89     重庆   支付宝  2025-08-25
293  5832560118   食品     薯片     7   19     北京   支付宝  2025-08-25
294  5880846456   服装    西装裤     9  449     昆明  微信支付  2025-08-25
300  6869253277   食品    方便面     1   49     北京   支付宝  2025-08-27
303  6806160339   食品  零食大礼包     3   89     青岛   支付宝  2025-08-29
304  6862175114   食品     面包     8   29     成都   支付宝  2025-08-29
308  5854096632   服装    牛仔裤     4  399     昆明   支付宝  2025-08-30
311  5855677494   食品     坚果    10   79     宁波   支付宝  2025-08-30
313  6833144246   食品    能量棒     5   49     厦门   支付宝  2025-08-31
314  6889158121   食品     牛奶    10   69     厦门  微信支付  2025-08-31
320  5830696359   食品     坚果     3   79     上海   支付宝  2025-09-01
323  5859034879   服装    连衣裙     9  499     武汉   支付宝  2025-09-02
324  5849308732   服装     风衣     5  699     厦门  微信支付  2025-09-03
325  6809660384   食品    矿泉水     5   29     北京  微信支付  2025-09-03
332  6836140342   食品  零食大礼包     1   89     郑州  微信支付  2025-09-06
334  5872942373   食品     饼干     8   39     厦门  微信支付  2025-09-06
340  5834735575   食品     酸奶     5   59     成都   支付宝  2025-09-08
341  6876402501   服装     睡衣    10  199     西安   支付宝  2025-09-08
351  5878252086   食品     肉脯     7   69     郑州   支付宝  2025-09-11
352  6826816957   服装     手套     5   59     北京   支付宝  2025-09-11
355  6818372908   服装     风衣     1  699     广州  微信支付  2025-09-13
356  6890163345   食品    矿泉水     9   29     南京   支付宝  2025-09-13
357  5866711381   食品     肉脯    10   69     成都   支付宝  2025-09-13
375  5844313707   服装     短裤     3  149     广州  微信支付  2025-09-19
377  5878946554   服装     手套     6   59     重庆  微信支付  2025-09-20
379  5852580673   食品     坚果     1   79     深圳   支付宝  2025-09-20
382  5844830398   食品     茶叶     9  199     郑州  微信支付  2025-09-21
387  6837647011   服装     卫衣    10  349     郑州  微信支付  2025-09-24
393  5867475720   服装     卫衣     9  349     广州   支付宝  2025-09-26
400  5863886364   服装     内衣     1   89     合肥  微信支付  2025-09-29
411  5833331680   食品     果汁     5   39     杭州  微信支付  2025-10-03
416  6805742005   服装    羽绒服     9  899     深圳  微信支付  2025-10-04
418  5800957347   服装     风衣     1  699     苏州   支付宝  2025-10-04
420  6891178336   服装     卫衣     7  349     南京  微信支付  2025-10-05
421  6822571575   食品    方便面    10   49     青岛   支付宝  2025-10-05
422  5867099128   服装     T恤     4  199     宁波   支付宝  2025-10-05
424  6872487503   食品     糖果     7   39     南京   支付宝  2025-10-05
434  5840421293   食品     茶叶    10  199     郑州   支付宝  2025-10-08
437  6876227672   食品    方便面    10   49     天津   支付宝  2025-10-08
441  6863254178   服装     短裤     3  149     长沙   支付宝  2025-10-12
447  6844659317   服装     卫衣     4  349     天津   支付宝  2025-10-13
450  5892891438   食品     麦片     5   49     天津   支付宝  2025-10-14
456  5852431984   服装     毛衣     5  399     上海  微信支付  2025-10-15
462  5830301956   服装     风衣    10  699     苏州   支付宝  2025-10-18
464  6800227885   食品     蜂蜜     4   89     杭州  微信支付  2025-10-18
472  6832768716   服装    羽绒服     6  899     杭州  微信支付  2025-10-20
474  6897454715   食品     面包     5   29     重庆   支付宝  2025-10-20
478  5861615084   食品     海苔     7   29     宁波   支付宝  2025-10-21
479  6887791768   食品  零食大礼包     7   89     重庆  微信支付  2025-10-22
486  6887669254   食品     果汁     9   39     天津   支付宝  2025-10-25
498  6859861779   服装     内衣     3   89     昆明  微信支付  2025-10-29
500  6806335545   服装     毛衣     8  399     福州   支付宝  2025-10-29
502  6891182351   食品     麦片     6   49     宁波   支付宝  2025-10-30
506  6881473885   服装     风衣     6  699     北京   支付宝  2025-11-01
508  5892304397   服装     睡衣     3  199     昆明  微信支付  2025-11-01
514  5807367507   食品     酸奶     2   59     上海   支付宝  2025-11-03
516  5870995622   食品     果汁     3   39     广州   支付宝  2025-11-03
521  5827669048   食品     麦片     6   49     南京   支付宝  2025-11-04
527  6890940588   服装    羽绒服     6  899     宁波   支付宝  2025-11-05
531  6824998019   服装     衬衫     6  299     广州  微信支付  2025-11-06
533  5801461172   食品     海苔     2   29     青岛   支付宝  2025-11-07
534  5888544474   食品     糖果     3   39     广州  微信支付  2025-11-07
541  5847381957   服装     毛衣     5  399     天津   支付宝  2025-11-08
544  6832194328   服装     袜子     4   29     上海   支付宝  2025-11-12
545  6859510952   食品     酸奶     1   59     福州   支付宝  2025-11-12
546  6843273729   食品     果汁     1   39     成都  微信支付  2025-11-12
550  5876901338   服装     短裤     6  149     苏州  微信支付  2025-11-13
554  6823002682   服装    牛仔裤     9  399     重庆   支付宝  2025-11-14
555  6814348900   食品     牛奶     2   69     杭州   支付宝  2025-11-14
556  6835195484   食品     坚果     1   79     郑州   支付宝  2025-11-14
562  6890733017   食品     蜂蜜     5   89     重庆   支付宝  2025-11-16
565  6805300350   服装     手套    10   59     天津   支付宝  2025-11-17
568  6810309738   服装    运动裤     9  249     成都   支付宝  2025-11-17
571  5899959087   服装     衬衫     5  299     重庆  微信支付  2025-11-18
576  5890932573   服装     卫衣     1  349     深圳   支付宝  2025-11-19
585  6840013941   食品     薯片    10   19     青岛  微信支付  2025-11-23
587  6805424379   食品     蜂蜜     2   89     昆明   支付宝  2025-11-24
601  6838249011   食品     牛奶     5   69     郑州  微信支付  2025-11-27
603  6888122019   食品     薯片     9   19     重庆   支付宝  2025-11-28
604  5814374624   服装     帽子     6   79     西安   支付宝  2025-11-28
606  6811426830   食品     果干     9   59     苏州  微信支付  2025-11-28
607  5808385307   服装     围巾     3  129     郑州   支付宝  2025-11-28
608  5826023717   食品    方便面    10   49     合肥  微信支付  2025-11-29
611  5851946844   服装    西装裤     2  449     广州   支付宝  2025-11-29
615  5801601835   食品     坚果     4   79     杭州   支付宝  2025-11-30
617  5805561986   食品     麦片     7   49     郑州  微信支付  2025-12-01
619  6814787700   食品     酸奶     2   59     南京   支付宝  2025-12-01
622  6826401287   食品     果汁     1   39     福州   支付宝  2025-12-02
628  6800844618   服装    半身裙     2  299     苏州   支付宝  2025-12-05
629  6881159219   食品  零食大礼包     9   89     青岛   支付宝  2025-12-05
630  6838456073   食品    能量棒     3   49     西安   支付宝  2025-12-05
637  5817801181   服装     外套     7  599     昆明  微信支付  2025-12-06
643  6882465065   食品     咖啡     8  129     杭州   支付宝  2025-12-09
645  5894722975   服装    西装裤     3  449     杭州   支付宝  2025-12-09
647  6800132162   食品    巧克力     7   59     南京   支付宝  2025-12-09
654  6824531780   食品     酸奶     2   59     武汉   支付宝  2025-12-11
659  5820099845   食品     面包     8   29     青岛  微信支付  2025-12-13
660  5894543795   食品     蜂蜜     2   89     深圳  微信支付  2025-12-13
661  6877207718   服装     睡衣    10  199     郑州   支付宝  2025-12-13
663  6889148565   服装    运动裤     5  249     福州   支付宝  2025-12-14
664  6890554963   食品     果汁     9   39     南京  微信支付  2025-12-14
665  5838827496   食品    矿泉水     8   29     昆明   支付宝  2025-12-15
674  5898811822   服装     衬衫     7  299     深圳  微信支付  2025-12-17
678  6858202357   食品     海苔     1   29     苏州   支付宝  2025-12-17
680  5818560820   服装    连衣裙     1  499     宁波   支付宝  2025-12-18
689  6837234220   服装     衬衫     9  299     宁波  微信支付  2025-12-21
690  5889119247   食品     酸奶     7   59     广州   支付宝  2025-12-21
692  5858127300   服装     毛衣    10  399     广州   支付宝  2025-12-22
694  6893767116   食品     肉脯     5   69     长沙   支付宝  2025-12-22
695  5821415588   服装     外套     7  599     宁波   支付宝  2025-12-22
697  5846696675   食品     海苔     6   29     武汉  微信支付  2025-12-23
703  6895808010   服装     衬衫     3  299     天津   支付宝  2025-12-27
711  6850905506   服装     手套     9   59     北京   支付宝  2025-12-28
712  5859112208   服装    牛仔裤     1  399     宁波   支付宝  2025-12-29
717  6863194415   食品    巧克力     2   59     广州  微信支付  2025-12-29
723  5873075759   服装     T恤     1  199     青岛   支付宝  2025-12-31
725  5885551427   服装     围巾     4  129     昆明  微信支付  2026-01-01
726  5878068551   食品     蜂蜜     1   89     长沙   支付宝  2026-01-01
727  5873037010   服装    运动裤     9  249     杭州   支付宝  2026-01-01
728  6887007128   食品    方便面     3   49     郑州   支付宝  2026-01-01
733  6846834565   食品     蜂蜜     8   89     厦门   支付宝  2026-01-02
736  5829134832   服装    羽绒服     8  899     郑州   支付宝  2026-01-02
737  5896329735   食品     牛奶     7   69     郑州  微信支付  2026-01-03
738  6876119129   服装     袜子     9   29     苏州   支付宝  2026-01-03
739  5861601703   服装     短裤     6  149     合肥   支付宝  2026-01-03
740  5800978577   食品     肉脯     1   69     杭州   支付宝  2026-01-03
743  6808516843   食品     糖果     8   39     郑州   支付宝  2026-01-04
746  6873188858   食品     面包     2   29     上海  微信支付  2026-01-05
749  6829708798   服装     毛衣    10  399     重庆   支付宝  2026-01-06
753  6850321380   食品    方便面     1   49     长沙   支付宝  2026-01-08
757  6894941319   食品     牛奶     2   69     深圳   支付宝  2026-01-09
759  5845135733   服装     风衣     5  699     上海   支付宝  2026-01-10
760  6802509590   服装    休闲裤    10  299     天津   支付宝  2026-01-10
761  5857737355   服装     帽子     5   79     武汉  微信支付  2026-01-11
764  6857397864   食品     酸奶     3   59     昆明   支付宝  2026-01-12
766  6881818665   食品     坚果     8   79     南京   支付宝  2026-01-12
771  6833832071   服装     外套     1  599     苏州  微信支付  2026-01-13
777  6819383488   食品     咖啡     8  129     杭州   支付宝  2026-01-15
778  6824898650   服装    西装裤     7  449     长沙   支付宝  2026-01-15
787  6873634429   服装     围巾     9  129     南京   支付宝  2026-01-19
788  5832767756   服装     睡衣     5  199     福州   支付宝  2026-01-19
794  5880271871   食品     薯片     4   19     厦门   支付宝  2026-01-21
798  5896831836   食品     蜂蜜     4   89     长沙   支付宝  2026-01-22
801  6882057428   服装     卫衣     8  349     合肥   支付宝  2026-01-22
802  6806158927   服装    半身裙     2  299     南京   支付宝  2026-01-23
803  6862339896   服装     袜子     6   29     西安   支付宝  2026-01-24
808  5836504290   服装     手套     1   59     广州  微信支付  2026-01-25
810  5859159196   服装     短裤     3  149     宁波  微信支付  2026-01-25
812  5804522125   食品     茶叶     4  199     合肥  微信支付  2026-01-25
815  6827507349   食品    方便面     1   49     厦门   支付宝  2026-01-25
816  6829037148   服装     手套     3   59     福州  微信支付  2026-01-26
817  6896371812   服装     内衣    10   89     成都   支付宝  2026-01-26
818  5861247566   服装     毛衣     2  399     青岛  微信支付  2026-01-26
825  5844362711   食品  零食大礼包     9   89     宁波  微信支付  2026-01-28
826  5852743923   服装     袜子    10   29     厦门   支付宝  2026-01-28
827  5886930931   食品     饼干     3   39     昆明   支付宝  2026-01-29
837  5847846135   服装    羽绒服     1  899     北京   支付宝  2026-02-01
838  6877703658   服装     短裤     4  149     宁波   支付宝  2026-02-02
848  6890989079   服装     围巾     9  129     广州  微信支付  2026-02-04
857  6880545195   服装    半身裙     7  299     厦门   支付宝  2026-02-06
858  5869018230   食品     果汁     5   39     青岛   支付宝  2026-02-07
862  5879388874   服装     帽子    10   79     福州  微信支付  2026-02-08
865  5889010874   服装     卫衣     1  349     厦门   支付宝  2026-02-09
866  5858336101   服装     毛衣     2  399     成都  微信支付  2026-02-09
869  6805587795   食品     咖啡     5  129     广州   支付宝  2026-02-10
872  5827187927   食品     坚果     2   79     北京  微信支付  2026-02-12
876  6868786229   服装     衬衫     3  299     宁波   支付宝  2026-02-13
877  6819364658   食品    能量棒     1   49     西安   支付宝  2026-02-13
879  5823878172   服装    羽绒服     3  899     郑州   支付宝  2026-02-13
881  5824441799   服装    牛仔裤    10  399     杭州  微信支付  2026-02-15
886  5845686917   食品    矿泉水    10   29     厦门   支付宝  2026-02-16
889  6814146241   服装     睡衣     5  199     武汉   支付宝  2026-02-16
893  5830454883   服装     衬衫     8  299     成都   支付宝  2026-02-18
895  6893665395   服装    西装裤     9  449     上海   支付宝  2026-02-18
897  6838816181   食品     海苔     3   29     福州  微信支付  2026-02-19
901  5822910476   服装     短裤     3  149     北京  微信支付  2026-02-21
903  5862381963   食品    巧克力     2   59     郑州   支付宝  2026-02-22
906  5815953258   食品     蜂蜜     1   89     苏州   支付宝  2026-02-23
907  5890411651   食品     茶叶     8  199     上海  微信支付  2026-02-23
910  5823746636   食品    矿泉水     1   29     西安   支付宝  2026-02-24
911  5813388774   食品     饼干     8   39     宁波   支付宝  2026-02-24
912  5836793818   服装     睡衣     6  199     西安  微信支付  2026-02-24
915  6828928851   食品    矿泉水     9   29     福州  微信支付  2026-02-25
916  5843842801   服装     内衣     9   89     西安  微信支付  2026-02-25
921  6859580477   食品     果汁    10   39     南京  微信支付  2026-02-26
923  6851255907   服装     围巾     9  129     长沙  微信支付  2026-02-27
924  6890368843   食品     牛奶     9   69     成都   支付宝  2026-02-28
926  5877260638   服装     卫衣     7  349     天津   支付宝  2026-02-28
927  5868549939   服装    休闲裤     5  299     南京   支付宝  2026-03-01
930  5865877696   食品     牛奶    10   69     重庆  微信支付  2026-03-01
932  5837665363   食品     茶叶     2  199     宁波  微信支付  2026-03-01
933  6842226211   服装     袜子     8   29     天津   支付宝  2026-03-01
935  5804771350   服装    牛仔裤     6  399     苏州   支付宝  2026-03-03
940  6827649901   食品     牛奶     3   69     上海  微信支付  2026-03-05
942  5800711405   服装    羽绒服    10  899     上海  微信支付  2026-03-06
943  5835405260   食品     饼干     4   39     天津  微信支付  2026-03-06
944  5820486804   服装     外套     8  599     南京   支付宝  2026-03-06
950  6840652306   食品     牛奶     2   69     北京  微信支付  2026-03-08
951  5811563987   服装     内衣     5   89     成都  微信支付  2026-03-08
952  5877681820   食品    巧克力     9   59     南京   支付宝  2026-03-08
955  6875099532   食品     果汁     1   39     武汉   支付宝  2026-03-09
959  5860412339   服装     毛衣     7  399     合肥   支付宝  2026-03-10
967  6848472509   食品     酸奶     1   59     杭州   支付宝  2026-03-12
968  6848495241   服装     袜子     7   29     昆明  微信支付  2026-03-12
972  5867305556   食品     肉脯     3   69     重庆  微信支付  2026-03-13
976  6835452753   食品     牛奶     2   69     青岛   支付宝  2026-03-14
978  5855860680   食品     蜂蜜     7   89     郑州  微信支付  2026-03-14
983  6890836887   服装     短裤     8  149     杭州   支付宝  2026-03-15
985  5862231814   服装     毛衣     6  399     厦门  微信支付  2026-03-15
988  6845708709   服装     衬衫     7  299     苏州   支付宝  2026-03-16
993  6870828210   服装     内衣     8   89     广州  微信支付  2026-03-20
994  5860722276   服装     外套     6  599     广州  微信支付  2026-03-20
996  5808511756   食品     坚果     2   79     成都   支付宝  2026-03-20
997  5811169466   服装     围巾     4  129     南京   支付宝  2026-03-20
998  6876456690   食品     果汁     7   39     广州   支付宝  2026-03-20