In [2]:
import pandas as pd

# 读取数据 --> read_csv
df = pd.read_csv('data/sales.csv', usecols=['订单号', '产品类别', '产品名称', '销售数量', '单价'])

# 数据处理
df['销售金额'] = df['销售数量'] * df['单价']

# 写入数据 --> to_csv --- index=False: 不写入索引列
df.to_csv('data/sales_01.csv', index=False)

In [33]:
# 数据查看 --> head , tail , describe , info , shape , columns
df1 = pd.read_csv('data/sales.csv', usecols=['订单号', '产品类别', '产品名称', '销售数量', '单价'])

df1.head(10) # 显示前10行数据
df1.tail(10) # 显示最后10行数据
df1.describe() # 显示数据统计信息
df1.info() # 显示数据信息(列名, 非空计数, 数据类型等)
df1.shape # 显示数据行数和列数
df1.columns # 显示列名

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   订单号     1000 non-null   int64
 1   产品类别    1000 non-null   object
 2   产品名称    1000 non-null   object
 3   销售数量    1000 non-null   int64
 4   单价      1000 non-null   int64
dtypes: int64(3), object(2)
memory usage: 39.2+ KB

Index(['订单号', '产品类别', '产品名称', '销售数量', '单价'], dtype='object')

In [52]:
# 数据选择
df2 = pd.read_csv('data/sales.csv', usecols=['订单号', '产品类别', '产品名称', '销售数量', '单价'], index_col='订单号')

# 1. 选择列
# 1.1 单列
# df2['产品名称']
# df2.产品名称

# 1.2 多列
# df2[['产品名称', '单价']]
# df2[['产品类别', '产品名称', '单价']]


# 2. 选择行 - iloc , loc
# 2.1 iloc ----> 基于行号选择行 (不包含结束位置) , 语法: df.iloc[start:stop:step]
# df2.iloc[0:5:1]
# df2.iloc[0:5]

# 2.2 loc ----> 基于行索引选择行 (包含结束位置) , 语法: df.loc[start:stop:step]
df2.loc[6805677496:5888085066:2]

            产品类别  产品名称  销售数量   单价
订单号
6805677496  家居用品    枕头    10  199
5888085059  电子产品  智能音箱     5  399
6801664364    食品    薯片     2   19
6857752388    服装    袜子     7  -29
5875402232  电子产品   路由器     9  299

In [3]:
df3 = pd.read_csv('data/sales.csv')

# 配置项, 展示所有的数据
# pd.set_option('display.max_rows', None)

# 数据过滤 ---> df[filter]
# 1. 获取 销售数量 >= 10 的订单数据
df3[df3['销售数量'] >= 10]

# 2. 获取产品类别为 食品 或 图书 的订单数据
df3[df3['产品类别'].isin(['食品', '图书'])]

# 3. 获取 单价在100-200之间 的订单数据 ---> 范围: between ---> 默认包含边界 (inclusive="left")
df3[df3['单价'].between(79, 199)]

# 4. 获取 销售数量 >= 8 , 并且 单价 >= 100 的订单数据 ----> 多条件(并且: & , 或者: |)
df3[(df3['销售数量'] >= 8) & (df3['单价'] >= 100)]

# 5. 获取 产品类别为 服装/食品 ， 支付方式为 支付宝/微信支付 的订单数据
df3[(df3['产品类别'].isin(['服装', '食品'])) & (df3['支付方式'].isin(['支付宝', '微信支付']))]

            订单号 产品类别 产品名称  销售数量   单价 客户所在城市  支付方式        订单日期
4    6801664364   食品   薯片     2   19    NaN  微信支付  2025/06/02
10   5808071569   食品  矿泉水     9   29     重庆   支付宝  2025-06-04
16   5812573980   食品   坚果     2   79     南京  微信支付  2025-06-05
23   6867258691   服装   围巾     8  129     青岛  微信支付  2025-06-07
25   6837065480   服装   毛衣     3  399     深圳  微信支付  2025-06-07
..          ...  ...  ...   ...  ...    ...   ...         ...
993  6870828210   服装   内衣     8   89     广州  微信支付  2026-03-20
994  5860722276   服装   外套     6  599     广州  微信支付  2026-03-20
996  5808511756   食品   坚果     2   79     成都   支付宝  2026-03-20
997  5811169466   服装   围巾     4  129     南京   支付宝  2026-03-20
998  6876456690   食品   果汁     7   39     广州   支付宝  2026-03-20

[297 rows x 8 columns]